# driver.yml

services:
  fastapi-sgx:
    build:
      context: ./fastapi 
      dockerfile: Dockerfile
    container_name: fastapi-spark-local-sgx
    network_mode: "host"
    environment:
      - IPFS_API_URL_ADD=${IPFS_API_URL_ADD:-http://127.0.0.1:5001/api/v0/add}
      - IPFS_API_URL_CAT=${IPFS_API_URL_CAT:-http://127.0.0.1:5001/api/v0/cat}
      - SPARK_UI_PORT=${SPARK_UI_PORT:-4040}
      - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
    devices:
      - "/dev/sgx_enclave:/dev/sgx_enclave"
    volumes:
      - ./data:/app/data
      - ./build:/app/build
    security_opt:
      - seccomp=unconfined
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
      - IPC_LOCK
    restart: unless-stopped

  ipfs:
    image: ipfs/kubo:latest
    container_name: ipfs-node
    network_mode: "host"
    volumes:
      - ./ipfs_data:/data/ipfs
    restart: unless-stopped

